apiVersion: v2
name: redis-user
type: application
annotations:
  category: Database
  licenses: Apache-2.0
version: 1.0.0
dependencies:
  - name: redis
    version: "17.7.1"
    repository: "https://charts.bitnami.com/bitnami"
