# architecture: standalone
# auth:
#   enabled: false
# master:
#   persistence:
#     size: 1Gi
#   service:
#     type: LoadBalancer
#     annotations:
#       networking.gke.io/load-balancer-type: "Internal"
architecture: standalone
auth:
  enabled: false
  sentinel: false
image:
  registry: docker.io
  repository: bitnami/redis
  tag: 7.0.7-debian-11-r0
  digest: ""
master:
  ## @param master.count Number of Redis&reg; master instances to deploy (experimental, requires additional configuration)
  ##
  count: 1
