architecture: standalone
auth:
  enabled: false
  sentinel: false
image:
  registry: docker.io
  repository: bitnami/redis
  tag: 7.0.7-debian-11-r0
  digest: ""
master:
  count: 1
  service:
    type: LoadBalancer
    annotations:
      networking.gke.io/load-balancer-type: "Internal"
