architecture: standalone
auth:
  enabled: false
master:
  persistence:
    size: 1Gi
  service:
    type: LoadBalancer
    annotations:
      networking.gke.io/load-balancer-type: "Internal"
metrics:
  enabled: true
# service:
# type: LoadBalancer
# annotations:
# networking.gke.io/load-balancer-type: "Internal"
